development:
  google:
    id: <%= ENV['GOOGLE_ANALYTICS_ID'].presence || nil %>

test:
  google:
    id: <%= ENV['GOOGLE_ANALYTICS_ID'].presence || nil %>

production:
  google:
    id: <%= ENV['GOOGLE_ANALYTICS_ID'].presence || nil %>
